/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload avatar */
        post: operations["UsersController_uploadAvatar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/avatar/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remove avatar */
        post: operations["UsersController_removeAvatar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_googleSignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get next upcoming alarm (for countdown) */
        get: operations["AlarmsController_getNext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of upcoming alarms */
        get: operations["AlarmsController_getUpcoming"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/past": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of past alarms */
        get: operations["AlarmsController_getPast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/sent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of sent alarms */
        get: operations["AlarmsController_getSent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a self alarm */
        post: operations["AlarmsController_createSelf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm friend alarm request */
        post: operations["AlarmsController_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject friend alarm request */
        post: operations["AlarmsController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/{id}/got": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark alarm as received (optionally with feedback message) */
        post: operations["AlarmsController_got"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/{id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss alarm */
        post: operations["AlarmsController_dismiss"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/{id}/snooze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snooze alarm */
        post: operations["AlarmsController_snooze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/{id}/video/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload video file for alarm */
        post: operations["AlarmsController_uploadVideo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/friends/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a friend alarm */
        post: operations["AlarmsController_setFriendAlarm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/{id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clone an alarm */
        post: operations["AlarmsController_cloneAlarm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get alarm details */
        get: operations["AlarmsController_getAlarm"];
        put?: never;
        post?: never;
        /** Delete alarm */
        delete: operations["AlarmsController_deleteAlarm"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/{id}/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update alarm */
        patch: operations["AlarmsController_updateSelfAlarm"];
        trace?: never;
    };
    "/api/v1/alarms/{id}/friend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update friend alarm (date/time only) */
        patch: operations["AlarmsController_updateFriendAlarm"];
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notifications with filters and pagination */
        get: operations["NotificationsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get notifications settings */
        get: operations["NotificationsController_getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update notifications settings */
        patch: operations["NotificationsController_updateSettings"];
        trace?: never;
    };
    "/api/v1/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my friends/requests */
        get: operations["FriendsController_list"];
        put?: never;
        /** Create friend request manually */
        post: operations["FriendsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/friends/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add friends from contact list (bulk import with validation and dedup) */
        post: operations["FriendsController_importContacts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register or update device push token */
        post: operations["DevicesController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserResponseDto: {
            /** @example 9f6c2fc9-936e-4dd9-9610-fd6f7da9425a */
            id: string;
            /** @example user@example.com */
            email?: string;
            /** @example Андрій Юрчук */
            name?: string;
            /** @example https://lh3.googleusercontent.com/a/ACg8ocIpKpeLRN4eCjevhdvABBECYo_UOmRvEqS-chtHoYw83ww9dQ=s96-c */
            avatarUrl?: string;
        };
        UserResponseWrapperDto: {
            /**
             * @description Indicates if the request was successful
             * @example true
             */
            success: boolean;
            /**
             * @description Response message or error detail
             * @example Request completed successfully
             */
            message: string;
            /** @description Actual data returned by the API, if any */
            data: components["schemas"]["UserResponseDto"];
        };
        GoogleSigninDto: {
            /**
             * @description Google ID token
             * @example ...
             */
            idToken: string;
        };
        GoogleSigninResponseDto: Record<string, never>;
        CreateSelfAlarmDto: {
            /**
             * @description Alarm date (YYYY-MM-DD)
             * @example 2025-09-19
             */
            date: string;
            /**
             * @description Alarm time (HH:mm, 24h)
             * @example 09:00
             */
            time: string;
            /**
             * @description Timezone string
             * @example Europe/Kyiv
             */
            timezone: string;
            /**
             * @description Recurring toggle
             * @example false
             */
            recurring: boolean;
            /**
             * @description Selected wake methods
             * @example [
             *       "VOICE",
             *       "VIDEO"
             *     ]
             */
            wakeMethods: ("VOICE" | "VIDEO" | "SONG" | "PUZZLE")[];
            /**
             * @description Voice URL
             * @example https://example.com/voice.mp3
             */
            voiceUrl: string;
            /**
             * @description Video URL
             * @example https://example.com/video.mp4
             */
            videoUrl: string;
            /**
             * @description Song URL
             * @example https://example.com/song.mp3
             */
            songUrl: string;
            /**
             * @description Puzzle image URL
             * @example https://example.com/puzzle.jpg
             */
            puzzleImageUrl: string;
            /**
             * @description Puzzle pieces
             * @example 2
             */
            puzzlePieces: number;
        };
        SelfAlarmResponseDto: {
            id: string;
            ownerId: string;
            /** @example 2025-10-15T14:57:26.218Z */
            scheduledAt: string;
            /** @example Europe/Kyiv */
            timezone: string;
            /** @enum {string} */
            frequency: "ONCE" | "RECURRING";
            /** @enum {string} */
            wakeMethods: "VOICE" | "VIDEO" | "SONG" | "PUZZLE";
            message?: Record<string, never> | null;
            voiceUrl?: Record<string, never> | null;
            videoUrl?: Record<string, never> | null;
            songUrl?: Record<string, never> | null;
            puzzleImageUrl?: Record<string, never> | null;
            puzzlePieces?: Record<string, never> | null;
            createdAt: string;
            updatedAt: string;
        };
        SelfAlarmResponseWrapperDto: {
            /**
             * @description Indicates if the request was successful
             * @example true
             */
            success: boolean;
            /**
             * @description Response message or error detail
             * @example Request completed successfully
             */
            message: string;
            /** @description Actual data returned by the API, if any */
            data: components["schemas"]["SelfAlarmResponseDto"];
        };
        AlarmGotDto: {
            /**
             * @description Optional feedback message
             * @example Nice wake-up!
             */
            message?: string;
        };
        /**
         * @description Snooze minutes - only 5, 10, or 15 minutes allowed
         * @enum {number}
         */
        SnoozeMinutes: 5 | 10 | 15;
        AlarmSnoozeDto: {
            /**
             * @description Snooze minutes - only 5, 10, or 15 minutes allowed
             * @example 10
             */
            minutes?: components["schemas"]["SnoozeMinutes"];
        };
        CreateFriendAlarmDto: {
            /** @description Owner user id (friend to be woken) */
            friendUserId?: string;
            /**
             * @description Alarm date (YYYY-MM-DD)
             * @example 2025-09-26
             */
            date: string;
            /**
             * @description Alarm time (HH:mm, 24h)
             * @example 09:00
             */
            time: string;
            /** @example Europe/Kyiv */
            timezone: string;
            /** @example false */
            recurring?: boolean;
            wakeMethods: ("VOICE" | "VIDEO" | "SONG" | "PUZZLE")[];
            /** @example https://example.com/voice.mp3 */
            voiceUrl?: string;
            /** @example https://example.com/video.mp4 */
            videoUrl?: string;
            /** @example https://example.com/song.mp3 */
            songUrl?: string;
            /** @example https://example.com/puzzle.jpg */
            puzzleImageUrl?: string;
            /** @example 9 */
            pieces?: number;
        };
        FriendAlarmResponseDto: {
            alarmId: string;
            /** @enum {string} */
            type: "SELF" | "FRIEND";
            /** @description ID friend user who will be woken */
            friendUserId: string;
            /** @description ID user who created the alarm */
            createdById: string;
            friendAlarmId?: Record<string, never> | null;
            requesterId?: Record<string, never> | null;
            /** @example 2025-10-15T14:57:26.216Z */
            scheduledAt: string;
            /** @example Europe/Kyiv */
            timezone: string;
            /** @enum {string} */
            frequency: "ONCE" | "RECURRING";
            wakeMethods: ("VOICE" | "VIDEO" | "SONG" | "PUZZLE")[];
            /** @enum {string} */
            approvalStatus: "PENDING" | "ACCEPTED" | "REJECTED" | "VIEWED";
            voiceUrl?: Record<string, never> | null;
            videoUrl?: Record<string, never> | null;
            songUrl?: Record<string, never> | null;
            puzzleImageUrl?: Record<string, never> | null;
            puzzlePieces?: Record<string, never> | null;
            /** @example 2025-10-15T14:57:26.217Z */
            createdAt: string;
            /** @example 2025-10-15T14:57:26.217Z */
            updatedAt: string;
        };
        FriendAlarmResponseWrapperDto: {
            /**
             * @description Indicates if the request was successful
             * @example true
             */
            success: boolean;
            /**
             * @description Response message or error detail
             * @example Request completed successfully
             */
            message: string;
            /** @description Actual data returned by the API, if any */
            data: components["schemas"]["FriendAlarmResponseDto"];
        };
        CloneAlarmDto: {
            /** @description Override: friend user id (target owner) */
            friendUserId?: string;
            /** @example 2025-10-01 */
            date?: string;
            /** @example 08:30 */
            time?: string;
            /** @example Europe/Kyiv */
            timezone?: string;
            /** @example false */
            recurring?: boolean;
            wakeMethods?: ("VOICE" | "VIDEO" | "SONG" | "PUZZLE")[];
            /** @example https://example.com/voice.mp3 */
            voiceUrl?: string | null;
            /** @example https://example.com/video.mp4 */
            videoUrl?: string | null;
            /** @example https://example.com/song.mp3 */
            songUrl?: string | null;
            /** @example https://example.com/puzzle.jpg */
            puzzleImageUrl?: string | null;
            /** @example 9 */
            pieces?: number | null;
        };
        UpdateAlarmDto: {
            /** @example 2025-10-01 */
            date?: string;
            /** @example 08:30 */
            time?: string;
            /** @example Europe/Kyiv */
            timezone?: string;
            /** @example false */
            recurring?: boolean;
            wakeMethods?: ("VOICE" | "VIDEO" | "SONG" | "PUZZLE")[];
            voiceUrl?: string;
            videoUrl?: string;
            songUrl?: string;
            puzzleImageUrl?: string;
            pieces?: number;
        };
        UpdateFriendAlarmDto: {
            /**
             * @description Date (YYYY-MM-DD)
             * @example 2025-10-01
             */
            date?: string;
            /**
             * @description Time (HH:mm)
             * @example 08:30
             */
            time?: string;
            /**
             * @description (IANA) Timezone
             * @example Europe/Kyiv
             */
            timezone?: string;
        };
        NotificationListWrapperDto: {
            /**
             * @description Indicates if the request was successful
             * @example true
             */
            success: boolean;
            /**
             * @description Response message or error detail
             * @example Request completed successfully
             */
            message: string;
            /** @description Actual data returned by the API, if any */
            data: Record<string, never>;
        };
        NotificationsSettingsDto: {
            /**
             * @description Notify when friend receives the request for alarm
             * @example true
             */
            notifyFriendRequestReceived: boolean;
            /**
             * @description Notify when friend confirmed your request for alarm
             * @example true
             */
            notifyFriendRequestConfirmed: boolean;
            /**
             * @description Notify when friend rejected your request for alarm
             * @example true
             */
            notifyFriendRequestRejected: boolean;
            /**
             * @description Notify when friend got your alarm
             * @example true
             */
            notifyFriendGotAlarm: boolean;
            /**
             * @description Notify when friend joined the app via your request
             * @example true
             */
            notifyFriendJoined: boolean;
            /**
             * @description Notify when friend suggested a different date
             * @example true
             */
            notifyFriendSuggestedChange: boolean;
            /**
             * @description Notify 30 minutes before the alarm
             * @example true
             */
            notifyBeforeAlarmInfo: boolean;
            /**
             * @description Notify when friend dismissed your alarm
             * @example true
             */
            notifyFriendDismissed: boolean;
            /**
             * @description Notify when friend snoozed your alarm
             * @example true
             */
            notifyFriendSnoozed: boolean;
        };
        NotificationsSettingsWrapperDto: {
            data: components["schemas"]["NotificationsSettingsDto"];
            /** @example true */
            success: boolean;
            /** @example Request completed successfully */
            message: string;
        };
        FriendResponseDto: {
            /** @example 6dbb9f7c-2a6b-4c7b-8b7b-0b4e6c2e1a33 */
            id: string;
            /** @example 9f6c2fc9-936e-4dd9-9610-fd6f7da9425a */
            userId: string;
            /** @example 1a2b3c4d-936e-4dd9-9610-fd6f7da9425a */
            friendUserId: string;
            /** @example PENDING */
            status: string;
        };
        FriendResponseListWrapperDto: {
            /**
             * @description Indicates if the request was successful
             * @example true
             */
            success: boolean;
            /**
             * @description Response message or error detail
             * @example Request completed successfully
             */
            message: string;
            /** @description Actual data returned by the API, if any */
            data: components["schemas"]["FriendResponseDto"][];
        };
        FriendResponseWrapperDto: {
            /**
             * @description Indicates if the request was successful
             * @example true
             */
            success: boolean;
            /**
             * @description Response message or error detail
             * @example Request completed successfully
             */
            message: string;
            /** @description Actual data returned by the API, if any */
            data: components["schemas"]["FriendResponseDto"];
        };
        ContactDto: {
            /** @example Robert Fox */
            name: string;
            /** @example +12085550112 */
            phone: string;
            /** @example https://example.com/avatar.jpg */
            avatarUrl?: string;
        };
        ImportContactsDto: {
            contacts: components["schemas"]["ContactDto"][];
        };
        RegisterDeviceDto: {
            /**
             * @description FCM push token
             * @example fcm-token-abc
             */
            pushToken: string;
            /**
             * @example IOS
             * @enum {string}
             */
            deviceType: "IOS" | "ANDROID";
            /** @example 1.0.0 */
            appVersion?: string;
            /** @example uk-UA */
            locale?: string;
        };
        RegisterDeviceResponse: {
            /**
             * @description Indicates if the request was successful
             * @example true
             */
            success: boolean;
            /**
             * @description Response message or error detail
             * @example Request completed successfully
             */
            message: string;
            /** @description Actual data returned by the API, if any */
            data: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseWrapperDto"];
                };
            };
        };
    };
    UsersController_uploadAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_removeAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleSigninDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleSigninResponseDto"];
                };
            };
        };
    };
    AlarmsController_getNext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlarmsController_getUpcoming: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlarmsController_getPast: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlarmsController_getSent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlarmsController_createSelf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSelfAlarmDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SelfAlarmResponseWrapperDto"];
                };
            };
        };
    };
    AlarmsController_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlarmsController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlarmsController_got: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlarmGotDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlarmsController_dismiss: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlarmsController_snooze: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlarmSnoozeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlarmsController_uploadVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlarmsController_setFriendAlarm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFriendAlarmDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendAlarmResponseWrapperDto"];
                };
            };
        };
    };
    AlarmsController_cloneAlarm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source alarm ID to clone */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CloneAlarmDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendAlarmResponseWrapperDto"];
                };
            };
        };
    };
    AlarmsController_getAlarm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendAlarmResponseWrapperDto"];
                };
            };
        };
    };
    AlarmsController_deleteAlarm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendAlarmResponseWrapperDto"];
                };
            };
        };
    };
    AlarmsController_updateSelfAlarm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAlarmDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendAlarmResponseWrapperDto"];
                };
            };
        };
    };
    AlarmsController_updateFriendAlarm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFriendAlarmDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendAlarmResponseWrapperDto"];
                };
            };
        };
    };
    NotificationsController_list: {
        parameters: {
            query?: {
                type?: "GENERAL" | "ALARM" | "SYSTEM";
                /** @description Filter by read status */
                read?: boolean;
                from?: string;
                to?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListWrapperDto"];
                };
            };
        };
    };
    NotificationsController_getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsSettingsWrapperDto"];
                };
            };
        };
    };
    NotificationsController_updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationsSettingsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsSettingsWrapperDto"];
                };
            };
        };
    };
    FriendsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendResponseListWrapperDto"];
                };
            };
        };
    };
    FriendsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @example Robert Fox */
                    name: string;
                    /** @example +12085550112 */
                    phone: string;
                    /**
                     * Format: uri
                     * @example https://example.com/avatar.jpg
                     */
                    avatarUrl?: string | null;
                    /** Format: binary */
                    avatar?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendResponseWrapperDto"];
                };
            };
        };
    };
    FriendsController_importContacts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportContactsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendResponseListWrapperDto"];
                };
            };
        };
    };
    DevicesController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeviceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterDeviceResponse"];
                };
            };
        };
    };
}
